<a href="https://colab.research.google.com/github/Vantage-hub/hamoye-quiz1/blob/master/electric_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv -O ucidata.csv

--2020-08-25 10:31:08--  https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2417871 (2.3M) [application/x-httpd-php]
Saving to: ‘ucidata.csv’

ucidata.csv         100%[===================>]   2.31M  4.52MB/s    in 0.5s

2020-08-25 10:31:08 (4.52 MB/s) - ‘ucidata.csv’ saved [2417871/2417871]

In [8]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import xgboost
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('ucidata.csv')
df

          tau1      tau2      tau3  ...        g4      stab     stabf
0     2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1     9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2     8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3     0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4     3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable
...        ...       ...       ...  ...       ...       ...       ...
9995  2.930406  9.487627  2.376523  ...  0.608385  0.023892  unstable
9996  3.392299  1.274827  2.954947  ...  0.366120 -0.025803    stable
9997  2.364034  2.842030  8.776391  ...  0.145984 -0.031810    stable
9998  9.631511  3.994398  2.757071  ...  0.818391  0.037789  unstable
9999  6.530527  6.781790  4.349695  ...  0.942631  0.045263  unstable

[10000 rows x 14 columns]

In [4]:
df.drop('stab', axis=1, inplace=True)
df

          tau1      tau2      tau3  ...        g3        g4     stabf
0     2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1     9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2     8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3     0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4     3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable
...        ...       ...       ...  ...       ...       ...       ...
9995  2.930406  9.487627  2.376523  ...  0.813512  0.608385  unstable
9996  3.392299  1.274827  2.954947  ...  0.285880  0.366120    stable
9997  2.364034  2.842030  8.776391  ...  0.149286  0.145984    stable
9998  9.631511  3.994398  2.757071  ...  0.889118  0.818391  unstable
9999  6.530527  6.781790  4.349695  ...  0.378761  0.942631  unstable

[10000 rows x 13 columns]

In [7]:
encoder = LabelEncoder()
df['stabf'] = encoder.fit_transform(df['stabf'])
df

          tau1      tau2      tau3  ...        g3        g4  stabf
0     2.959060  3.079885  8.381025  ...  0.887445  0.958034      1
1     9.304097  4.902524  3.047541  ...  0.562139  0.781760      0
2     8.971707  8.848428  3.046479  ...  0.839444  0.109853      1
3     0.716415  7.669600  4.486641  ...  0.929381  0.362718      1
4     3.134112  7.608772  4.943759  ...  0.656947  0.820923      1
...        ...       ...       ...  ...       ...       ...    ...
9995  2.930406  9.487627  2.376523  ...  0.813512  0.608385      1
9996  3.392299  1.274827  2.954947  ...  0.285880  0.366120      0
9997  2.364034  2.842030  8.776391  ...  0.149286  0.145984      0
9998  9.631511  3.994398  2.757071  ...  0.889118  0.818391      1
9999  6.530527  6.781790  4.349695  ...  0.378761  0.942631      1

[10000 rows x 13 columns]

In [10]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X

          tau1      tau2      tau3  ...        g2        g3        g4
0     2.959060  3.079885  8.381025  ...  0.859578  0.887445  0.958034
1     9.304097  4.902524  3.047541  ...  0.862414  0.562139  0.781760
2     8.971707  8.848428  3.046479  ...  0.766689  0.839444  0.109853
3     0.716415  7.669600  4.486641  ...  0.976744  0.929381  0.362718
4     3.134112  7.608772  4.943759  ...  0.455450  0.656947  0.820923
...        ...       ...       ...  ...       ...       ...       ...
9995  2.930406  9.487627  2.376523  ...  0.779642  0.813512  0.608385
9996  3.392299  1.274827  2.954947  ...  0.567242  0.285880  0.366120
9997  2.364034  2.842030  8.776391  ...  0.986505  0.149286  0.145984
9998  9.631511  3.994398  2.757071  ...  0.587558  0.889118  0.818391
9999  6.530527  6.781790  4.349695  ...  0.505441  0.378761  0.942631

[10000 rows x 12 columns]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_test

          tau1      tau2      tau3  ...        g2        g3        g4
9953  6.877876  4.113820  9.356768  ...  0.845536  0.112440  0.822562
3850  5.802841  6.271371  4.731540  ...  0.416478  0.912846  0.861306
4962  2.286998  4.385142  2.830232  ...  0.130186  0.703887  0.063811
3886  5.019920  2.209962  6.266080  ...  0.065992  0.427349  0.814648
5437  7.646145  9.187896  5.484219  ...  0.121611  0.787318  0.300314
...        ...       ...       ...  ...       ...       ...       ...
3919  8.320531  3.394352  1.468729  ...  0.493384  0.178907  0.173240
162   2.290102  3.028512  8.071234  ...  0.770194  0.234290  0.225070
7903  7.848945  0.684889  0.728223  ...  0.559799  0.682418  0.886902
2242  2.173967  5.776797  4.597638  ...  0.743103  0.152161  0.305183
2745  1.467618  9.389085  6.019740  ...  0.273217  0.526145  0.851163

[2000 rows x 12 columns]

In [14]:
rforest = RandomForestClassifier(random_state=1)
X_train = X_train.values
y_train = y_train.values

In [15]:
X_train

array([[6.25599523, 2.54240096, 7.02471361, ..., 0.61840292, 0.68573895,
        0.6600877 ],
       [5.07058071, 5.49025308, 8.07568836, ..., 0.09724393, 0.91695454,
        0.12925353],
       [1.22007238, 8.80402796, 3.87428286, ..., 0.9235942 , 0.23888068,
        0.6601562 ],
       ...,
       [7.05255981, 3.26405709, 1.40594941, ..., 0.60556602, 0.10059087,
        0.74731999],
       [5.08524173, 1.79003062, 2.48639191, ..., 0.41851155, 0.32625269,
        0.98248766],
       [1.20535385, 6.99504458, 5.93086002, ..., 0.20276838, 0.84837263,
        0.73999336]])

In [ ]:
rforest.fit(X_train, y_train)